import "./globals.css";
import Provider from "@/components/queryclientprovider";
import type { Metadata } from "next";
import { Poppins, Balsamiq_Sans } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/theme-provider";
import { GlocalContextProvider } from "@/components/contextProvoder";

const poppins = Poppins({ subsets: ["latin", "latin-ext"], weight: "400" });
const balsamiq = Balsamiq_Sans({
   style: "normal",
   weight: "400",
   subsets: ["cyrillic"],
});

export const metadata: Metadata = {
   title: "Modlk",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <Provider>
            <body className={`${balsamiq.className} w-screen min-h-[100dvh]`}>
               <GlocalContextProvider>
                  <ThemeProvider
                     attribute="class"
                     defaultTheme="dark"
                     enableSystem
                     disableTransitionOnChange
                  >
                     {children}
                  </ThemeProvider>
               </GlocalContextProvider>
               <Toaster />
            </body>
         </Provider>
      </html>
   );
}
