import type { Metadata } from "next";
import { Inter, IBM_Plex_Sans } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import Sidebar from "./(component)/sidebar";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });
const ibmPlex = IBM_Plex_Sans({ subsets: ["latin"], weight: "500" });

export const metadata: Metadata = {
   title: "Modlk",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body
            className={`${ibmPlex.className} w-screen min-h-[100dvh] grid grid-cols-[auto_1fr]`}
         >
            <ThemeProvider
               attribute="class"
               defaultTheme="dark"
               enableSystem
               disableTransitionOnChange
            >
               <Sidebar />
               {children}
            </ThemeProvider>
            <Toaster />
         </body>
      </html>
   );
}
