import "./globals.css";
import type { Metadata } from "next";
import { Inter, IBM_Plex_Sans } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { GlocalContextProvider } from "@/components/contextProvoder";
import Provider from "@/components/queryclientprovider";

const inter = Inter({ subsets: ["latin"] });
const ibmPlex = IBM_Plex_Sans({ subsets: ["latin"], weight: "500" });

export const metadata: Metadata = {
    title: "Modlk",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <Provider>
                <body
                    className={`${ibmPlex.className} w-screen min-h-[100dvh]`}
                >
                    <GlocalContextProvider>
                        <ThemeProvider
                            attribute="class"
                            defaultTheme="dark"
                            enableSystem
                            disableTransitionOnChange
                        >
                            {children}
                        </ThemeProvider>
                    </GlocalContextProvider>
                    <Toaster />
                </body>
            </Provider>
        </html>
    );
}
